apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsmutant
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: thecalifornia16/node_devops
        ports:
        - containerPort: 3000
       
---
apiVersion: v1
kind: Service
metadata:
  name: devopsmutant-service
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: helloworld
