apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: devops_mutant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops_mutant
  template:
    metadata:
      labels:
        app: devops_mutant
    spec:
      containers:
      - name: devops_mutant
        image: thecalifornia16/node_devops
        ports:
        - containerPort: 8080
       
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: devops_mutant
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32121
  selector:
    app: devops_mutant
